### ISSUE TITLE
Add images or presentation slides

### ISSUE THREAD

**Issue by jaller94** [Liptoon/eichhoernchen-shdb2019#2]
As someone who has not heard about the project, I want to get an idea of what this project is about.

Please add images and/or your presentation slides to help others understand your project.

**Comment by squeezer44** [comment]
Same for me: I only  understand your project on a high level because I've been a guest in your project talk yesterday. 
Also for me: presentation slides (maybe as a wiki page inside this repo?) would be fantastic personally for me and it could also increase the level of awareness.

**Comment by squeezer44** [comment]
That caould support the project understanding: https://nutjob-docs.glitch.me/
